# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/masfiyan/Athestia/key_internal_new/key_internal_new.cache/wt [current_project]
set_property parent.project_path /home/masfiyan/Athestia/key_internal_new/key_internal_new.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/masfiyan/Athestia/key_internal_new/key_internal_new.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Bitpack_new.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Chi.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/CoefFromHalfByte.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Coefficient_three_bytes.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Dilithium_pkg.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/ExpandA.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/ExpandS.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Iota.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Keccak.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/KeyGen.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/NTT.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/NTT_INV.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Pad10_1.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Pi.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Power2round.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/RejBoundedPoly.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/RejNttPoly.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Rho.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Round.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/SKEncode.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Shake.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/SimpleBitPack.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/Theta.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/key_internal.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/pkEncode.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/rand.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/swapbits.sv
  /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/sources_1/new/topp.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files /home/masfiyan/Athestia/key_internal_new/key_internal_new.srcs/constrs_1/new/constraint.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top topp -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topp_utilization_synth.rpt -pb topp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
