#!/bin/bash

# Check if the correct number of arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <SV_module_name> <CPP_file_name>"
    exit 1
fi

SV_MODULE_NAME=$1
CPP_FILE_NAME=$2

# Compile the SystemVerilog file with Verilator
verilator -Wall --trace -cc "${SV_MODULE_NAME}.sv" --exe "${CPP_FILE_NAME}.cpp"

# Build the simulation
make -j -C obj_dir -f "V${SV_MODULE_NAME}.mk" "V${SV_MODULE_NAME}"

# # Run the simulation
./obj_dir/"V${SV_MODULE_NAME}"

# Uncomment the following line to view the waveform with GTKWave
# gtkwave "${SV_MODULE_NAME}.vcd"


