webtalk_init -webtalk_dir C:/Users/msame/Desktop/Athestia/sign_internal/sign_internal.sim/sim_1/behav/xsim/xsim.dir/sign_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep 13 17:40:18 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "16992282-c679-4bc7-a0f0-09e6ab441720" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c627d3d1b0814b82a6c575b1a6371563" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "139.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "3207932_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2849833676 -regid "" -xml C:/Users/msame/Desktop/Athestia/sign_internal/sign_internal.sim/sim_1/behav/xsim/xsim.dir/sign_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/msame/Desktop/Athestia/sign_internal/sign_internal.sim/sim_1/behav/xsim/xsim.dir/sign_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/msame/Desktop/Athestia/sign_internal/sign_internal.sim/sim_1/behav/xsim/xsim.dir/sign_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
