webtalk_init -webtalk_dir H:/Store_Athestia/Athestia/update_Sample_in_ball/update_Sample_in_ball.sim/sim_1/behav/xsim/xsim.dir/tb_Sample_in_ball_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 16 18:06:39 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a272f623-52de-46a1-b77d-d4ba828f54e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71cbf9b9e39946b4852ee7bc566c11d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 72803005 -regid "" -xml H:/Store_Athestia/Athestia/update_Sample_in_ball/update_Sample_in_ball.sim/sim_1/behav/xsim/xsim.dir/tb_Sample_in_ball_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/Store_Athestia/Athestia/update_Sample_in_ball/update_Sample_in_ball.sim/sim_1/behav/xsim/xsim.dir/tb_Sample_in_ball_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/Store_Athestia/Athestia/update_Sample_in_ball/update_Sample_in_ball.sim/sim_1/behav/xsim/xsim.dir/tb_Sample_in_ball_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
