webtalk_init -webtalk_dir /home/mlatif/Athestia/ff2_part2_hintbitpack/ff2_part2_hintbitpack.sim/sim_1/behav/xsim/xsim.dir/HintBitPack_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 21 09:09:50 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9c7c8f2-d281-410a-83ae-8af72a0019f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ad3a265808024307845952d4429ad68f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "119" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2128.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "168.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "422 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114380_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1972114192 -regid "" -xml /home/mlatif/Athestia/ff2_part2_hintbitpack/ff2_part2_hintbitpack.sim/sim_1/behav/xsim/xsim.dir/HintBitPack_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mlatif/Athestia/ff2_part2_hintbitpack/ff2_part2_hintbitpack.sim/sim_1/behav/xsim/xsim.dir/HintBitPack_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mlatif/Athestia/ff2_part2_hintbitpack/ff2_part2_hintbitpack.sim/sim_1/behav/xsim/xsim.dir/HintBitPack_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
